"""add products and types

Revision ID: decaa0bf0e96
Revises: e936b401baf4
Create Date: 2020-05-15 01:03:37.523069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decaa0bf0e96'
down_revision = 'e936b401baf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.NVARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typeId', sa.Integer(), nullable=False),
    sa.Column('name', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('description', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('photo', sa.NVARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['typeId'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('email', sa.NVARCHAR(length=100), nullable=True))
    op.add_column('customers', sa.Column('name', sa.NVARCHAR(length=100), nullable=False))
    op.add_column('customers', sa.Column('phone', sa.NVARCHAR(length=10), nullable=False))
    op.create_foreign_key(None, 'options', 'products', ['productId'], ['id'])
    op.create_foreign_key(None, 'orders', 'products', ['productId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'options', type_='foreignkey')
    op.drop_table('products')
    op.drop_table('types')
    # ### end Alembic commands ###
